# Generated by Django 6.0.3 on 2026-04-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='estimates/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parser_errors', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('material_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('labor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['article'], name='estimates_e_article_5010f1_idx'), models.Index(fields=['name'], name='estimates_e_name_a3aeff_idx')],
            },
        ),
    ]
