# Generated by Django 6.0.3 on 2026-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimate_column_mapping_estimate_parse_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='matching_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='matching_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
