# Generated by Django 6.0.3 on 2026-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
