# Generated by Django 6.0.3 on 2026-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_lists', '0002_pricelist_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='parse_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
