# Generated by Django 6.0.3 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_lists", "0003_pricelist_parse_task_id_pricelist_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="matching_progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="matching_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="matching_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="match_confidence",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="match_method",
            field=models.CharField(
                blank=True,
                choices=[("ai", "AI"), ("manual", "Manual")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("matched", "Matched"),
                    ("needs_review", "Needs review"),
                    ("not_matched", "Not matched"),
                    ("manual", "Manual"),
                ],
                default="not_matched",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
