# Generated by Django 6.0.3 on 2026-04-06 09:00

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
    ]
