# Generated by Django 6.0.3 on 2026-04-06 09:05

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_enable_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="catalog_item_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
