# Generated by Django 6.0.3 on 2026-04-06 16:00

from django.db import migrations, models


def populate_normalized_name(apps, schema_editor):
    CatalogItem = apps.get_model("catalog", "CatalogItem")
    for catalog_item in CatalogItem.objects.all().iterator():
        normalized_name = " ".join((catalog_item.name or "").strip().lower().split())
        CatalogItem.objects.filter(pk=catalog_item.pk).update(normalized_name=normalized_name)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_catalogitem_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=500),
        ),
        migrations.RunPython(populate_normalized_name, migrations.RunPython.noop),
    ]
