# Generated by Django 6.0.3 on 2026-04-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('no_match', 'No match')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('manual', 'Manual'), ('article', 'By article'), ('fuzzy', 'Fuzzy')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_matches', to='catalog.catalogitem')),
                ('estimate_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='estimates.estimateitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
