# Generated by Django 6.0.3 on 2026-04-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_alter_estimateitemmatch_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimateitemmatch",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("article", "By article"),
                    ("embedding", "By embedding"),
                ],
                max_length=20,
            ),
        ),
    ]
