# Generated by Django 6.0.3 on 2026-04-06 14:20

from django.db import migrations, models


def migrate_match_methods(apps, schema_editor):
    EstimateItemMatch = apps.get_model("matching", "EstimateItemMatch")
    EstimateItemMatch.objects.filter(method__in=["embedding", "article"]).update(method="ai")


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_alter_estimateitemmatch_method"),
    ]

    operations = [
        migrations.RunPython(migrate_match_methods, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="estimateitemmatch",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("ai", "AI"),
                ],
                max_length=20,
            ),
        ),
    ]
