# Generated by Django 6.0.3 on 2026-04-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
